// This snippet file was generated by processing the source file:
import { initializeApp } from "firebase/app";

import{
    getFirestore, collection, getDocs, snapshotEqual,
    addDoc, query, where
} from 'firebase/firestore';
const firebaseConfig = {
    apiKey: "AIzaSyBcLT-qr1zh_njkS0y1SesLY2L7dF9-P3M",
    authDomain: "team4-5632d.firebaseapp.com",
    projectId: "team4-5632d",
    storageBucket: "team4-5632d.appspot.com",
    messagingSenderId: "44761875007",
    appId: "1:44761875007:web:3630b10e855f37432aae8a"
  };
  
  // Initialize Firebase
  initializeApp(firebaseConfig);

// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START simple_queries_modular]
// Create a reference to the cities collection
//import { collection, query, where } from "firebase/firestore";

const db = getFirestore();
const citiesRef = collection(db, "flights");

// Create a query against the collection.
const q = query(collection(db, "flights"), where("outgoing", "==", "Chicago"));
// [END simple_queries_modular]
console.log("query")

const querySnapshot = getDocs(q)
.then((snapshot)=>{
    snapshot.forEach((doc)=>{
        console.log(doc.data())

    })
})
//querySnapshot.forEach((doc) => {
  // doc.data() is never undefined for query doc snapshots
  //console.log(doc.id, " => ", doc.data());
//});