// This snippet file was generated by processing the source file:
import { initializeApp } from "firebase/app";

import{
    getFirestore, collection, getDocs, snapshotEqual,
    addDoc, query, where
} from 'firebase/firestore';
const firebaseConfig = {
    apiKey: "AIzaSyBcLT-qr1zh_njkS0y1SesLY2L7dF9-P3M",
    authDomain: "team4-5632d.firebaseapp.com",
    projectId: "team4-5632d",
    storageBucket: "team4-5632d.appspot.com",
    messagingSenderId: "44761875007",
    appId: "1:44761875007:web:3630b10e855f37432aae8a"
  };
  
  // Initialize Firebase
  initializeApp(firebaseConfig);




const db = getFirestore();
const citiesRef = collection(db, "flights");

// const city = document.querySelector(".value");
const city = "NYC"

const cidy = document.querySelector(".select");

cidy.addEventListener("submit",(event) =>{
    event.preventDefault();
    cidy.outgoing.value;
    console.log(cidy.outgoing.value);
     }
)


const q = query(collection(db, "flights"), where("outgoing", "==", city));




const querySnapshot = getDocs(q)
.then((snapshot)=>{
    snapshot.forEach((doc)=>{
        console.log(doc.data())

    })
})
getDocs(q)
    .then((snapshot)=>{
        let flight = [];
        let i = 0;
            snapshot.docs.forEach((documents)=>{
                flight.push({...documents.data(),id: documents.id});
                let table = document.getElementById('flights');
                let row = table.insertRow(-1);

                let cell = row.insertCell(0);
                let text = document.createTextNode(flight[i].outgoing);
                cell.appendChild(text);

                cell = row.insertCell(1);
                text = document.createTextNode(flight[i].incoming);
                cell.appendChild(text);
                cell = row.insertCell(2);
                text = document.createTextNode(flight[i].aircraft);
                cell.appendChild(text);

                cell = row.insertCell(3);
                text = document.createTextNode(flight[i].duration);
                cell.appendChild(text);

                i++;
            });
            console.log(flight);
    })
    .catch(err =>{
    console.error(err);
    });
// Create a query against the collection.

// function returnflights(city){
//     const q = query(collection(db, "flights"), where("outgoing", "==", city));
//     // [END simple_queries_modular]
//     console.log(q)
//     return q    
// }

// returnflights("Chicago")
// const city = document.querySelector(".select");
// console.log(city)
// city.addEventListener('submit', (event)=>{
//     event.preventDefault();
//     query(collection(db, "flights"), where("outgoing", "==", city))
// })

// const q = query(collection(db, "flights"), where("outgoing", "==", city));
// // [END simple_queries_modular]
// console.log(q)


